name: onenote_to_excel
description: Convert OneNote files to Excel using AI
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.4.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  http: ^1.1.0
  excel: ^4.0.0
  win32: ^5.0.9
  ffi: ^2.1.0
  provider: ^6.1.1
  flutter_markdown: ^0.6.18
  xml: ^6.3.0
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true